#!/bin/bash

username=$1

useradd -m $username
adduser $username sudo

apt update
apt install -y git

userhome="/home/${username}"

mkdir -p $userhome/workspace
mkdir -p $userhome/.ssh

rm -rf $userhome/workspace/linux-bootstrap
git clone https://github.com/rafaelzimmermann/linux-bootstrap.git $userhome/workspace/linux-bootstrap

chown -R $username: $userhome

cd $userhome/workspace/linux-bootstrap/
./bootstrap

echo "Defining $username passwd"
passwd $username


