#!/bin/bash

linode_index=$(linode-cli linodes ls --json | jq ".[].id" | wc -l)

read -p "Root passwd: " rootpass

linode_id=$(\
  linode-cli linodes create \
    --authorized_users tmpfile \
    --backups_enabled false \
    --booted true \
    --firewall_id 307432 \
    --image 'linode/ubuntu23.10' \
    --label "ubuntu-nl-ams-${linode_index}" \
    --private_ip false \
    --region nl-ams \
    --root_pass "${rootpass}" \
    --type g6-nanode-1 \
    --json \
    --suppress-warnings |\
  jq ".[].id")

echo ""
echo "Linode ${linode_id}"
echo ""

echo "Waiting node to change state to running"
echo ""

status=$(linode-cli linodes view $linode_id --json --suppress-warnings | jq ".[].status" | xargs echo -n)
echo $status
until [ "${status}" == "running" ]; do
  new_status=$(linode-cli linodes view $linode_id --json --suppress-warnings | jq ".[].status" | xargs echo -n)
  echo -n "."
  sleep 1
  if [ "${status}" != "${new_status}" ]; then
    status="${new_status}"
    echo ""
    echo "${status}"
  fi
done


linode_ip=$(linode-cli linodes view $linode_id --json --suppress-warnings | jq -r ".[].ipv4[0]")

echo "Waiting server to starting listening ssh port"
echo ""

while ! ssh "root@${linode_ip}" 'uptime'
do
    echo -n "."
    sleep 1
done

echo ""